name: hold_to_confirm_button
description: "A customizable hold-to-confirm button for Flutter applications."
repository: https://github.com/monster555/hold_to_confirm_button
homepage: https://github.com/monster555/hold_to_confirm_button

version: 0.0.2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4

topics:
  - animation
  - ui

flutter:

  uses-material-design: true
